services:
  app:
    build: ./backend/
    volumes:
      - ./backend/app/app:/home/app_user/app
      - ./backend/app/requirements.txt:/home/app_user/requirements.txt
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-m", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--app-dir", "app", "--log-level","debug"]

  db:
    build: ./backend/database/
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: "/backend/.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: