FROM python:alpine3.18
RUN apk --no-cache add curl
RUN addgroup -S python

RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/home/python/" \
    --ingroup "python" \
    --no-create-home \
    --uid "1000" \
    "python"

USER python

WORKDIR /home/python/

COPY requirements.txt .
RUN pip install -r requirements.txt
CMD ["python", "-m", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--app-dir", "app", "--log-level","debug"]