CREATE TABLE event (
    id SERIAL PRIMARY KEY,
    start_timestamp TIMESTAMPTZ NOT NULL,
    end_timestamp TIMESTAMPTZ NOT NULL,
    all_day BOOLEAN NOT NULL,
    url VARCHAR[100] NOT NULL,
    description VARCHAR NOT NULL,
    address VARCHAR NOT NULL,
    archived BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
